name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-generators:
    name: Test
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [16.x]    

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node.js dependencies globally
        run: |
          npm install
          npm install --global

      - name: test-generators-pull_request
        run: npm run test:generators
        continue-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.json
        
# compare against last commit to master as this will prevent a dip
# in results giving a pass when an extra test passes but previously extra 10 failed


      - name: Download previous test results
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: test.yml
          branch: master
          name: test-results
          path: CICD
      
      
      - name: Compare test results
        run: |
          ls
          cd CICD
          ls
