name: Test Forge

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test-forge:
    name: Test Forge
    runs-on: windows-latest 

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

        # Must change shell because this workflow uses the windows-latest image 
      - name: Set npm shell
        run: npm config set script-shell "C:\\Program Files\\Git\\bin\\bash.exe"

      - name: Install openapi-forge dependencies locally
        run: |
          npm install

      - name: Test Forge
        run: |
          npm run test:javascript
        continue-on-error: true
